### ISSUE TITLE
Maven task launcher should use a deployment triggered by a build

### ISSUE THREAD

**Issue by donovanmuller** [donovanmuller/spring-cloud-deployer-openshift#21]
Currently builds use a Watch to look for `Complete` builds and then extract the `outputDockerImageReference` to use as the image name for a bare Pod:

```
status:
  phase: Complete
  startTimestamp: '2016-11-23T14:15:01Z'
  completionTimestamp: '2016-11-23T14:15:34Z'
  duration: 33000000000
  outputDockerImageReference: '172.30.104.62:5000/test/task-0934448d-962a-4711-nw5yznodrr:latest' 
```

However, sometimes the `outputDockerImageReference` is not populated after a completed build which causes the image to be empty and the launch to fail:

```
java.lang.IllegalArgumentException: An image name is required
```

We should look into moving to the same mechanism used for app deployments.
Use a DeploymentConfig triggered by the build. The issue with this is the cleanup of the DeploymentConfig after the Pod has completed. This might be a non issue though...
