### ISSUE TITLE
Group related app Services in a stream

### ISSUE THREAD

**Issue by donovanmuller** [donovanmuller/spring-cloud-deployer-openshift#8]
Using the Service grouping feature of the OpenShift Console, group all stream related app's Service for easier viewing.

Like:

```
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: "xxx"
      name: "xxx"
      annotations:
        service.alpha.openshift.io/dependencies: '[{"name": "yyy","kind": "Service"}]'
```
